### ISSUE TITLE
[Bug Report] Rematches rewrite update has made this not work at all

### ISSUE THREAD

**Issue by Snahkstrasza** [NumyAddon/BlizzMovePlugin_Rematch#2]
With Rematchs rewrite back in November (Rematch_5_0_0) this no longer allows Blizzmove to work with Rematch

**Comment by Numynum** [comment]
should work fine now
though it seems to already work pretty well, even without the plugin 🤔

**Comment by Snahkstrasza** [comment]
Yeah it did its just the far right area that couldnt be dragged.
